# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('carriage_mass', models.FloatField()),
                ('no_load_torque', models.FloatField()),
                ('pulley_circumference_mm', models.IntegerField()),
                ('max_applied_load_Fy', models.IntegerField()),
                ('max_applied_load_Fz', models.IntegerField()),
                ('max_moment_Mx', models.IntegerField()),
                ('max_moment_My', models.IntegerField()),
                ('max_moment_Mz', models.IntegerField()),
                ('max_stroke_mm', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('max_acc', models.IntegerField()),
                ('max_effective_action_force_lt_1', models.IntegerField()),
                ('max_effective_action_force_in_1_3', models.IntegerField()),
                ('max_effective_action_force_gt_3', models.IntegerField()),
            ],
        ),
    ]
