# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchingEngine', '0002_auto_20170321_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='max_acc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='max_moment_Mx',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='max_moment_My',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='max_moment_Mz',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='max_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
